### ISSUE TITLE
Transitive dependency on specific versions of urllib3

### ISSUE THREAD

**Issue by nshgraph** [honeycombio/libhoney-py#141]
**Versions**

- Python: 3.8
- Libhoney: current

**Steps to reproduce**

1. libhoney relies on `requests = "^2.24.0"`
2. requests 2.24 relies on `urllib3>=1.21.1,<1.27`
3. libhoney _actually_ relies on urllib3>=1.26.12 which introduces 'allowed_methods' to  urllib3.util.Retry (used in transmission.py)

libhoney should really list all actual dependencies (not rely on transitive) and should specify the versions correctly.

**Additional context**

**Comment by nshgraph** [comment]
It looks like this transitive dependency was introduced last month (https://github.com/honeycombio/libhoney-py/pull/126) which is why we are experiencing broken builds now...

**Comment by emilyashley** [comment]
Ah, thank you for taking the time to report this @nshgraph - I didn't realize it had fallen through the cracks with that update!

**Comment by nshgraph** [comment]
Thank you :-)
