### ISSUE TITLE
Consider supporting `nan` as input or better reporting on an error when that is the case

### ISSUE THREAD

**Issue by cartermp** [honeycombio/libhoney-py#163]
This was copied over from a prodpad filing. I think it probably just belongs here:

> It seems the literal `nan` is not allowed by your JSON decoder on the server side. You might want to file a ticket for your team that develops libhoney-py to restrict emitting JSON that has `nan` in it. One way to do that is to pass `json.dumps(..., allow_nan=False, ...)`. It would also be great if you would add some reporting when that fails to isolate which payload in the batch is the problem. And finally, it would be great if the server's 400 response mentioned the problem was JSON decoding, just to rule out throttling or gzip or bad headers or any other issue.

The user had a numeric field that was `nan` and we just spat out this error:

> ` json decoding error: invalid character 'N' looking for beginning of value.`

Could probably do better here.

**Comment by kentquirk** [comment]
This is interesting...a while back, I fixed libhoney to not issue NaN or inf.

Valid JSON does not include NaN, -Inf, or Inf as valid values for floats, but the parser Honeycomb uses supports them if you send them as quoted strings. So this:

```
$ curl -X POST -H "Content-Type: application/json" --header "X-Honeycomb-Team:$KEY" --data '{"test":0, "foo":NaN, "bar":124.4}' "https://api-dogfood.honeycomb.io/1/events/jsontest"
{"error":"request body is malformed and cannot be read"}
```
but this works:
```
$ curl -X POST -H "Content-Type: application/json" --header "X-Honeycomb-Team:$KEY" --data '{"test":0, "foo":"NaN", "bar":124.4}' "https://api-dogfood.honeycomb.io/1/events/jsontest"
```

**Comment by kentquirk** [comment]
Modifying shepherd to emit a better error message would require replacing the JSON parser for all of Shepherd with another one, which has unknown performance and customer impact. It doesn't seem to be justified to try to fix this to cope with a rare error case when someone sends bad data. 

Similarly, libhoney-py uses the json marshaller in the standard library, which incorrectly encodes NaN into JSON. The libhoney-py library could be changed to have a new json serializer that supports not serializing NaN -- but that seems unlikely to happen given that we're mostly not changing libhoney libraries any more.

So I'm closing this as "won't fix". Please reopen if you can make a case for fixing it.
