### ISSUE TITLE
Re-usable Pluggable Django Middleware

### ISSUE THREAD

**Issue by zoidbergwill** [honeycombio/libhoney-py#23]
A while ago I fiddled with making a Django middleware that makes it easier to add honeycomb to Django projects, basically just moving one of the Django examples into the package, so you can add it to a project using the following:

```
MIDDLEWARE_CLASSES = (
    # ...
    'libhoney.contrib.django.middleware.HoneyMiddleware',
)
```

Would it be worth making a PR or a separate package for this? I can write tests and clean up the required and optional/dynamic fields then too.

[`django-prometheus`](https://github.com/korfuri/django-prometheus#quickstart) and [Sentry](https://docs.sentry.io/clients/python/integrations/django/) include similar modules.

 https://github.com/honeycombio/libhoney-py/compare/master...zoidbergwill:django-middleware?expand=1

P.S.: Sorry if I missed an issue discussing this.

**Comment by nathanleclaire** [comment]
Hey there @zoidbergwill. We think this sounds like a great idea! We suggest making a new repository called `honeycomb-django` and publishing your work there. This repository is intended for the core `libhoney` functionality.

**Comment by nathanleclaire** [comment]
Give us a ping if you do so ;) We always love to see blog articles about that sort of thing as well.

**Comment by zoidbergwill** [comment]
Awesome, thanks. Will do that. 👍 🙏
