### ISSUE TITLE
ncclient equivalent??

### ISSUE THREAD

**Issue by kawshiksark** [honeycombio/libhoney-py#27]
Hi , 

I have used **ncclient** (netconf client) previously to configure my juniper/dell or cisco devices. I just allows your python script to leverage on a library to get basic get,Edit etc operations on your device. Is libhoney used in the same way?

if so are there any examples of a sample script. To do say a basic get or edit config?

**Comment by mollystamos123** [comment]
Hi - 

Honeycomb is not a network configuration product - we track application events to measure things like performance, etc. We don't get network device configs at all. 

Wondering if you've got us confused with someone else :)

**Comment by kawshiksark** [comment]
hi thanks for your reply nathan. Is this the same honeycomb agent thats
used to configure VPP and has a subcomponent called hc2vpp?
Because that one  is definitely an agent that allows configuration and
network monitoring from ODL controllers.

https://wiki.fd.io/view/Honeycomb

BR
KAwshik
