### ISSUE TITLE
Python SDK returning errors when sending events

### ISSUE THREAD

**Issue by AwsGeek** [honeycombio/libhoney-py#30]
The python SDK is returning errors when I run the sample code to add an event:

{'body': '', 'status_code': 0, 'duration': 0.1239776611328125, 'metadata': None, 'error': TypeError("request() got an unexpected keyword argument 'json'",)}

The issue seems to in transmission.py, here:
           resp = self.session.post(
                url,
                headers={"X-Honeycomb-Team": destination.writekey},
                json=payload)

Changed this to:

           resp = self.session.post(
                url,
                headers={"X-Honeycomb-Team": destination.writekey},
                data=json.dumps(payload))

and it appears to be working.

**Comment by emfree** [comment]
Thanks for the report! This should be fixed by #31.
