### ISSUE TITLE
LICENSE lacks filled-in Copyright holder

### ISSUE THREAD

**Issue by porterctrlz** [honeycombio/libhoney-py#5]
Heyo,

I would change this in a PR, but I feel like it should be sorted out upstream by you nice folks (though I'm not a lawyer :P).

Thanks,
Porter

**Comment by maplebed** [comment]
Hi Porter,

Thanks for bringing this up! I am also NAL, but I'll bring it up with the
team. There is the COPYRIGHT file in the repo, but I don't know how they're
supposed to interact. Maybe we just delete the section after END OF
TERMS... in the LICENSE file? Anyway. We'll sort it out.

Thanks for your PR!

-ben

**Comment by porterctrlz** [comment]
Looks like this was fixed :)
