### ISSUE TITLE
Buildevents prevents forked builds from running on CI

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/libhoney-py#78]
**Versions**

- Python: N/A
- Libhoney: main

**Steps to reproduce**
1. PRs submitted from a fork will fail because we build events is enabled and requires a CircleCI token which is not provided on forked runs.

**Additional context**
- We have removed build events from other repos because of this limitation.

As seen in #77

**Comment by vreynolds** [comment]
Should be fixed by #89
